import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navigation/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import MobileNavigation from "@/components/navigation/MobileNavigation";
import Footer from "@/components/navigation/Footer";

const inter = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const revalidate = 5;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth selection:bg-primary selection:text-white"
    >
      <body
        className={
          (cn("relative text-muted-foreground overflow-x-hidden"),
          inter.className)
        }
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <MobileNavigation />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
